apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtool
  template:
    metadata:
      labels:
        app: loadtool
    spec:
      containers:
        - name: loadtool
          image: loadtool:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONSUL_ADDRESS
              value: "http://host.docker.internal:8500"
