apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtool
  template:
    metadata:
      labels:
        app: loadtool
    spec:
      containers:
        - name: loadtool
          image: analytics-load-tool:latest
          imagePullPolicy: Never
          command: ["/app/loadtool"]
          args: ["druid-demo.log", "My_Try.loadtool_logs"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-volume
              mountPath: /app/druid-demo.log
              subPath: druid-demo.log
      volumes:
        - name: log-volume
          configMap:
            name: log-config
